
- name: install dev packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
   - clang-format
   - cmake
   - cppcheck
   - llvm
   - ninja
   - pyenv
   - pyenv-virtualenv
   - python3
   - byobu
   - shellcheck
   - tree
   - wget
   - the_silver_searcher
  tags: [dev]

- name: add pyenv setup to ${HOME}/.zshrc
  lineinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    state: present
    line: 'eval "$(pyenv init -)"'
  tags: [dev]

- name: add pyenv virtualenv setup to ${HOME}/.zshrc
  lineinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    state: present
    line: 'eval "$(pyenv virtualenv-init -)"'
  tags: [dev]

- name: install dev casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
   - alacritty
   - fork
  tags: [dev]