- name: install dev homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
   - clang-format
   - cmake
   - cppcheck
   - llvm
   - ninja
   - pyenv
   - pyenv-virtualenv
   - python3
   - shellcheck
   - the_silver_searcher
   - tmux
   - tree
   - wget
  tags: [dev]

- name: add pyenv setup to ${HOME}/.zshrc
  lineinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    state: present
    line: 'eval "$(pyenv init -)"'
  tags: [dev]

- name: add pyenv virtualenv setup to ${HOME}/.zshrc
  lineinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    state: present
    line: 'eval "$(pyenv virtualenv-init -)"'
  tags: [dev]

# TODO: Move python version to group vars
- name: install pyenv python 3.7.3
  shell: pyenv install 3.7.3
  tags: [dev]

- name: install dev casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
   - alacritty
   - fork
  tags: [dev]

- name: setup alacritty config
  copy:
    src: 'config/alacritty.yml'
    dest: '{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml'
  tags: [dev]