- name: install dev homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
   - clang-format
   - cmake
   - cppcheck
   - llvm
   - ninja
   - pyenv
   - pyenv-virtualenv
   - shellcheck
   - the_silver_searcher
   - tmux
   - tree
   - wget
  tags: [dev]
