- name: install usr packages
  homebrew:
    name: '{{ item }}'
    state: present
  with_items:
   - youtube-dl
  tags: [usr]

- name: install usr casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items:
   - fork
   - gimp
   - google-backup-and-sync
   - google-chrome
   - iterm2
   - macpass
   - qbittorrent
   - the-unarchiver
   - virtualbox
   - virtualbox-extension-pack
   - vlc
  tags: [usr]