- name: install zsh
  homebrew:
    name: '{{ item }}'
    state: present
  with_items:
   - wget
   - zsh
  tags: [zsh]

- name: check for oh-my-zsh
  stat:
    path: '{{ ansible_env.HOME }}/.oh-my-zsh'
  register: file_details
  tags: [zsh]

- name: install oh-my-zsh if not found
  shell: "sh -c '$(wget -O- https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)'"
  when: file_details.stat.exists == false
  tags: [zsh]

- name: mkdir ${HOME}/.dotfiles
  file:
    path: '{{ ansible_env.HOME }}/.dotfiles'
    state: directory

- name: copy zshrc
  copy:
    src: 'dotfiles/zshrc'
    dest: '{{ ansible_env.HOME }}/.dotfiles/zshrc'
  tags: [zsh]

- name: add "source ${HOME}/.dotfiles/zshrc" to ${HOME}/.zshrc
  lineinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    state: present
    line: 'source ${HOME}/.dotfiles/zshrc'
  tags: [zsh]

- name: install alacritty
  homebrew_cask:
    name: "alacritty"
    state: present
  tags: [zsh]

- name: mkdir ${HOME}/.config/alacritty
  file:
    path: '{{ ansible_env.HOME }}/.config/alacritty'
    state: directory

- name: copy alacritty config
  copy:
    src: 'dotfiles/alacritty.yml'
    dest: '{{ ansible_env.HOME }}//alacritty.yml'
  tags: [zsh]

- name: copy tmux config
  copy:
    src: 'dotfiles/tmux.conf'
    dest: '{{ ansible_env.HOME }}/.dotfiles/tmux.conf'
  tags: [zsh]

- name: symlink tmux config
  file:
    src: '{{ ansible_env.HOME }}/.dotfiles/tmux.conf'
    dest: '{{ ansible_env.HOME }}/.tmux.conf'
    state: link
  tags: [zsh]